SRCS	= ft_atoi.c ft_bzero.c ft_calloc.c ft_isalnum.c ft_isalpha.c ft_isascii.c ft_isdigit.c ft_isprint.c ft_itoa.c ft_memchr.c ft_memcmp.c ft_memcpy.c ft_memmove.c ft_memset.c ft_putchar_fd.c ft_putendl_fd.c ft_putnbr_fd.c ft_putstr_fd.c ft_split.c ft_strchr.c ft_strdup.c ft_striteri.c ft_strjoin.c ft_strlcat.c ft_strlcpy.c ft_strlen.c ft_strmapi.c ft_strncmp.c ft_strnstr.c ft_strrchr.c ft_strtrim.c ft_substr.c ft_tolower.c ft_toupper.c ft_printf.c ft_printf_utils_csp.c ft_printf_utils_diux.c get_next_line.c get_next_line_utils.c free_chartab.c ft_long_atoi.c ft_strcpy.c
BNSSRCS = ft_lstnew.c ft_lstadd_front.c ft_lstsize.c ft_lstlast.c ft_lstadd_back.c ft_lstdelone.c ft_lstclear.c ft_lstiter.c ft_lstmap.c get_next_line_bonus.c get_next_line_utils_bonus.c
OBJS	= ${SRCS:.c=.o}
BNSOBJS = ${BNSSRCS:.c=.o}
NAME	= libft.a
CC		= gcc
CFLAGS	= -Wall -Wextra -Werror
RM		= rm -f

all: ${NAME}
	@echo "Compiling libft"

%.o: %.c
	@${CC} ${CFLAGS} -c $< -o $@

$(NAME): ${OBJS}
	@ar -rc $(NAME) ${OBJS}

bonus: ${OBJS} ${BNSOBJS}
	@ar -rc $(NAME) ${OBJS} ${BNSOBJS}

clean:
	@${RM} ${OBJS} ${BNSOBJS}
	@echo "Cleaning libft"	

fclean: clean
	@echo "Fcleaning libft"
	@${RM} $(NAME) bonus

re: fclean all

.PHONY: all clean fclean re bonus	






